### ISSUE TITLE
kong config not following --link conventions?

### ISSUE THREAD

**Issue by bortels** [Mashape/docker-kong#10]
It appears "cassandra" is hard-wired as the hostname for the cassandra database. Using --link, the IP and port is available to the container - but it appears the config file does not expand environment variables? It would be nice if --link was sufficient without having to use a hardcoded name and export the cassandra port explicitly.

**Comment by bortels** [comment]
So - I'm lame. I didn't realize that the environment was not the only way --link passed data; the hostname, at least, is also in /etc/hosts, but I had named my cassandra container differently so missed that. While full-on support for arbitrary hosts and posts would be lovely - this is an enhancement, at best, not an issue. I will close it, and if someone wants to run with the idea, neato.

**Comment by omarvelous** [comment]
Just came across this same issue, however using docker-compose. I think an env variable would be better overall, but I can just modify my own fork I suppose.
