### ISSUE TITLE
Missing example for docker kong + docker host webserver

### ISSUE THREAD

**Issue by sloev** [Mashape/docker-kong#13]
I miss an example for adding an api running on the docker host.
It took me quite a long time to figure out that your upstream_url has to be pointing to the docker bridge ip of the docker host (if running docker in bridge mode)
I know that this might not be new knowledge to people with docker experience, but arriving at docker for running kong i missed the following example:

maybe an example could be python based:
if kong is running in docker and the docker host has ip 172.17.42.1 on the docker bridge interface.

    (get docker host bridge ip with: ifconfig docker0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}' )

make simple html index:
   
    cd /tmp/
    echo "hello world" > index.html

start api endpoint server:

    sudo python -m SimpleHTTPServer 9876

add it to kong:

    curl -i -XPOST "http://127.0.0.1:8001/apis/" --data 'name=example' --data     
    'upstream_url=http://172.17.42.1:9876/' --data 'request_host=example.com' 

test it out 

    curl -XGET --header 'Host: example.com' "http://localhost:8000/"

and it prints:
"hello world"

**Comment by sloev** [comment]
without the index.html the SimpleHTTPServer will just list current directory and output as html

**Comment by thefosk** [comment]
You could also link the final API container with Kong, and use the assigned name in the upstream_url hostname.
