### ISSUE TITLE
Note on Kong in docker with docker-machine on Mac OS X or Windows

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/docker-kong#14]
Hi guys,

When following the instructions for getting kong up and running on docker from scratch (the one at https://getkong.org/install/docker/), you run into the following little thing when on Mac OS X or Windows, which actually use VirtualBox for running the `default` image as docker host: The `curl` on localhost will not work, as the actual docker host is not localhost, but the docker host inside VirtualBox.

Instead, you have to issue your `curl` command against the IP your `$DOCKER_HOST` connection points to. Then it'll work. With my installation on Windows, that's

`curl http://192.168.99.100:8001`

This might not be an issue for anyone beyond n00b status, but I stumbled over it and had to give it some extra thought...

Best regards,
Martin

**Comment by thibaultCha** [comment]
Yes we are aware and assume minimal knowledge of Docker. Thanks.
