### ISSUE TITLE
Docker compose issues + possible solution.

### ISSUE THREAD

**Issue by tecnobrat** [Mashape/docker-kong#15]
Trying to use this image in a docker-compose setup with cassandra is impossible. The issue is that cassandra takes so long to startup and kong bails if cassandra isn't running.

I solved this by adding monit to the base image https://hub.docker.com/r/articulate/kong-monit/ and https://github.com/articulate/docker-kong-monit

We could easily roll this back into this repo by creating a secondary `Dockerfile.monit` and then having docker hub build that along with the other `Dockerfile`.  The normal one will be tagged how it is right now, but we can have the monit version tagged as `monit-latest` and `monit-0.5.3`.

This gives the person using the image the choice.

I'd be happy to PR the changes and work with whoever needed to get this done.

**Comment by thefosk** [comment]
I am not an expert of Compose, but I think somebody suggested using `restart: always` as a way to get around this problem.

**Comment by tecnobrat** [comment]
You are right, `restart: always` fixes this perfectly.

Closing.
