### ISSUE TITLE
Container exits immediately upon successful start

### ISSUE THREAD

**Issue by siddharthist** [Mashape/docker-kong#16]
I have a custom Kong configuration and Cassandra instance running. Kong succesfully connects to my database, and logs `[OK] Started`, but then immediately exits with status 0. This happens when the container is started from Marathon, or manually. My logs and configuration can be found [here](http://pastebin.com/raw/fGXS9XLv), scroll to the bottom for the manual run.

I know the Cassandra database to be good, I can manually connect to it using `cqlsh`.

Any pointers? Any ideas why this might happen? Or how I can debug?

**Comment by siddharthist** [comment]
This happens with any of the kong 0.5* versions, whereas any older than 0.5.0 complain "no contact points provided".

**Comment by thibaultCha** [comment]
Sorry I don't have time to further help you as I am on mobile, but just a thought: if you are not running your container in daemon mode, you might want to turn the `daemon` directive off in the nginx configuration:

```
daemon off;
```

That will keep nginx on the foreground. However, this directive is intended only for Nginx development and should not be used for production. Otherwise, run your container in daemon mode.

**Comment by siddharthist** [comment]
@thibaultCha I have to do a little more testing, but it looks like that fixes the problem! If that's the case, maybe there should be documentation around using this container on Mesos re: nginx daemonization? Why is that directive not for use in production?

**Comment by thibaultCha** [comment]
It is simply not recommended by Nginx: http://nginx.org/en/docs/faq/daemon_master_process_off.html

**Comment by thibaultCha** [comment]
At the same time, the Nginx image on Docker hub says:

> Be sure to include daemon off; in your custom configuration to ensure that Nginx stays in the foreground so that Docker can track the process properly (otherwise your container will stop immediately after starting)!

https://hub.docker.com/_/nginx/

So, well... I guess it is fine!

**Comment by siddharthist** [comment]
Well, I suppose we've solved my issue here. It might be good to document that under "2. Use Kong with a custom configuration (and Cassandra cluster)", though!

**Comment by mars** [comment]
This Nginx `daemon off` trick no longer works with Kong 0.6.0. It may appear to run, but one or two things will be amiss depending on config:

  * Serf will not be running
  * if Nginx is configured with `error_log stderr` or `stdout`, the streams are buffered by Lua and will not appear to the parent process until Nginx exits

With `daemon off`, Nginx [the start command blocks Lua](https://github.com/Mashape/kong/blob/0.6.0/kong/tools/io.lua#L33) until exit, and so [the next service Serf](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/utils/services.lua#L16) will not be started until Nginx exits (ever?)

With `demon on` the process exits immediately:
```bash
~ $ kong start -c config/kong.yml &
[1] 24
~ $ [INFO] Kong 0.6.0
[INFO] Using configuration: config/kong.yml
[INFO] database...........cassandra password=… data_centers= ssl=verify=true certificate_authority=/app/config/cassandra.cert enabled=true replication_factor=3 replication_strategy=SimpleStrategy contact_points=… username=… keyspace=…
[INFO] dnsmasq............port=8053 dnsmasq=true address=127.0.0.1:8053
[INFO] Auto-generating the default SSL certificate and key...
[INFO] nginx .............proxy_listen_ssl=0.0.0.0:12346 proxy_listen=0.0.0.0:12345 admin_api_listen=127.0.0.1:8001
[INFO] serf ..............-log-level=err -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/app/nginx-working/serf_event.sh -rpc-addr=127.0.0.1:7373 -bind=… -node=… -profile=wan
[INFO] Trying to auto-join Kong nodes, please wait..
[WARN] Cannot auto-join the cluster because no nodes were found
[OK] Started

[1]+  Done                    kong start -c config/kong.yml
```

With `demon off` the process seems to start-up:
```bash
~ $ kong start -c config/kong.yml &
[1] 16
~ $ Configuring as Kong proxy
[INFO] Kong 0.6.0
[INFO] Using configuration: config/kong.yml
[INFO] database...........cassandra password=… data_centers= ssl=verify=true certificate_authority=//app/config/cassandra.cert enabled=true replication_factor=3 replication_strategy=NetworkTopologyStrategy contact_points=… username=… keyspace=…
[INFO] dnsmasq............port=8053 dnsmasq=true address=127.0.0.1:8053
[INFO] Auto-generating the default SSL certificate and key...

```

…but stderr/stdout goes silent, and the cluster is offline:
```bash
~ $ kong cluster reachability -c config/kong.yml
[INFO] Using configuration: config/kong.yml
[ERR] serf is not running

```

…then stopping Kong results in Serf starting as the process exits:
```bash
~ $ kong stop -c config/kong.yml
[INFO] Using configuration: config/kong.yml


^C[INFO] Leaving cluster..
[OK] Stopped
[INFO] nginx .............proxy_listen_ssl=0.0.0.0:12346 proxy_listen=0.0.0.0:12345 admin_api_listen=127.0.0.1:8001
~ $ [INFO] serf ..............-log-level=err -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/app/nginx-working/serf_event.sh -rpc-addr=127.0.0.1:7373 -bind=… -node=… -profile=wan
[INFO] Trying to auto-join Kong nodes, please wait..
[WARN] Cannot auto-join the cluster because no nodes were found
[OK] Started

[1]+  Done                    kong start -c config/kong.yml
```

**Comment by thibaultCha** [comment]
Could a short-term solution be to start Serf *before* Nginx in Kong's services? I am not sure why it is not already the case tbh.

> if Nginx is configured with error_log stderr or stdout, the streams are buffered by Lua and will not appear to the parent process until Nginx exits

That is definitely what might be happening here, some investigation inside ngx_lua is required.

**Comment by mars** [comment]
Changing the service order to have nginx start last may indeed solve this.
