### ISSUE TITLE
Can Not Stop and re-start exiting container

### ISSUE THREAD

**Issue by esatterwhite** [Mashape/docker-kong#20]
With the current Docker file ( 0.6.0 ), you can't create a container in the background `-d`, stop it and restart it. Kong always complains about dnsmasq is still running.

I'm pretty certain it is the way the default `CMD` is set 

```bash
CMD kong start && tail -f /usr/local/kong/logs/error.log
```

This makes `tail` the command that docker is interacting with when you run `docker stop` so kong never shuts down properly. 

I think the default kong.yml should set nginx `daemon on` and kong start should be set as the command.

**Comment by esatterwhite** [comment]
This is also causing problems with clustering. There seems to be stale data some where as all of the new nodes I start try to register to an IP that no longer exists. 

The cluster command from the cli doesn't show it so I'm not sure how to resolve this problem

**Comment by thefosk** [comment]
This has been fixed with 0.7.0, where the old model (and no `tail`) is being used. If you confirm, we can close this issue.

**Comment by esatterwhite** [comment]
Confirmed.
