### ISSUE TITLE
no space left

### ISSUE THREAD

**Issue by gottfrois** [Mashape/docker-kong#23]
Seems that running kong and cassandra in docker containers eat disk space until there is no space left on my virtual machine.

Running `df -h` on the kong container: `docker exec kong df -h`

```
Filesystem      Size  Used Avail Use% Mounted on
none             48G   16G   29G  36% /
tmpfs           2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda1        48G   16G   29G  36% /etc/kong
shm              64M     0   64M   0% /dev/shm
```

At some point `/dev/sda1` will go up 100% use. Cassandra/Kong logs does not show anything particular. Any idea what might be wrong?

Using `cassandra:2.2.5` image and `mashape/kong` image. Also `docker info` shows:

```
Containers: 15
 Running: 2
 Paused: 0
 Stopped: 13
Images: 55
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 232
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: dinghy
ID: IOWU:RZYU:5UA3:FX4Z:K7TZ:APJV:STOA:PKBT:DFAY:575B:SEJT:JR2S
Debug mode (server): true
 File Descriptors: 36
 Goroutines: 61
 System Time: 2016-02-17T14:22:12.045636927Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: gottfrois
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Note: Running only cassandra image does not go up 100% disk use. It seems that it's kong that eat the disk space.

**Comment by thefosk** [comment]
Are the `access_log` turned on in Kong?

**Comment by gottfrois** [comment]
I don't think so https://github.com/Mashape/docker-kong/blob/master/config.docker/kong.yml#L26

**Comment by thefosk** [comment]
@gottfrois maybe the error logs are growing like crazy? Could you check the `error.log` file?

**Comment by mars** [comment]
@gottfrois would you run the following disk usage to find the biggest nodes in the filesystem?

```bash
du -a / | sort -n -r | head -n 50
```

**Comment by gottfrois** [comment]
@thefosk definitely not the logs:

```
$ docker exec -it e53a1078b5f27f31c8f4883ebec85d0a775d6fcb39e558127c4562dd80cf1777 ls -lh /usr/local/kong/logs
total 4.0K
-rw-r--r-- 1 root root  0 Feb 22 09:49 access.log
-rw-r--r-- 1 root root 59 Feb 22 09:50 error.log
```

@mars run the command in the kong container and got this:

```
docker exec -it e53a1078b5f27f31c8f4883ebec85d0a775d6fcb39e558127c4562dd80cf1777 du -a / | sort -n -r | head -n 50
2057268	/
1776704	/tmp
1776660	/tmp/serf.log
...
```

That should give you the file responsible? Let me know what I can do.

**Comment by mars** [comment]
`serf.log` is one of Kong's logs.

**Comment by mars** [comment]
That Serf error looks like `cluster_listen` in kong.yml cannot be bound in the container. https://github.com/Mashape/kong/blob/master/kong.yml

**Comment by gottfrois** [comment]
On a related note, aren't we supposed to expose `7373` port as well? I see it's defined in the conf but not in the dockerfile nor when running `docker run`

**Comment by thefosk** [comment]
Port `7373` is just used internally, so no need to expose it. 

Could you paste a few lines of the contents of `serf.log`? Really curious to figure out what does the log say.

**Comment by mars** [comment]
`serf.log` re-pasted from above:

```
$ docker exec -it e53a1078b5f27f31c8f4883ebec85d0a775d6fcb39e558127c4562dd80cf1777 tail -n 100 /tmp/serf.log
    2016/02/22 09:56:51 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:7946: accept4: operation not permitted
    2016/02/22 09:56:51 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:7946: accept4: operation not permitted
    2016/02/22 09:56:51 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:7946: accept4: operation not permitted
```

**Comment by thefosk** [comment]
Interesting, I have never seen this error before, give me some time to investigate.

**Comment by mars** [comment]
That `serf.log` error indicates that it's trying to bind to all IPv6 interfaces `[::]:7946`.

Re: IPv6, the [Serf docs](https://www.serfdom.io/docs/agent/options.html) say:

> Note: To use an IPv6 address, specify "[::1]" or "[::1]:7946".

**Comment by thefosk** [comment]
I think somebody else mentioned an issue with Serf binding, so something wrong may be happening. From the Serf doc linked by @mars, I assumed that by default (`0.0.0.0:7946`) Serf would bind to an IPv4 address, since the doc explicitly says that to bind to an IPv6 address we need to specify `[::1]:7946`.

Here it seems like although we are explicitly binding serf to ``0.0.0.0:7946` (instead of `::1:7946`), he is still trying to use an IPv6 address.

**Comment by mars** [comment]
It looks like the container must be run w/ `--ipv6` flag to support `[::]`

https://docs.docker.com/engine/userguide/networking/default_network/ipv6/#how-ipv6-works-on-docker

**Comment by thefosk** [comment]
@mars nice finding. 

On a side note @gottfrois are you explicitly trying to bind an IPv6 address, or you are just using the default `0.0.0.0:7946` value for the `cluster_listen` configuration setting (if the property is commented out, then it will default to `0.0.0.0:7946`) ?

**Comment by gottfrois** [comment]
@thefosk not touching any configurations. Using defaults values.

@mars how the `--ipv6` option should be used? Not sure to understand that from the documentation and my skills on docker are not that good yet :)

**Comment by mars** [comment]
@gottfrois `--ipv6` is an option for the Docker daemon, which starts & supervises containers.

The docker info you pasted above shows Boot2Docker 1.10.1. As far as I can tell, [Boot2Docker does not start the daemon with the `--ipv6` option](https://github.com/boot2docker/boot2docker/blob/v1.10.1/rootfs/rootfs/usr/local/etc/init.d/docker#L108).

I'm befuddled as to how that Serf IP address is being transformed from `0.0.0.0:7946` to `[::]:7946`.

**Comment by tfmalt** [comment]
Hi, I'm observing the same problem. After four minutes running the serf log file is > 2GB large
```
[root@9cf1d2623316 kong]# ls -l /tmp/serf.log
-rw-r--r-- 1 root root 2316070385 Feb 23 23:47 /tmp/serf.log
```

I've run the docker daemon with --ipv6 flags enabled.
```
CGroup: /system.slice/docker.service
           ├─17146 /usr/bin/docker daemon --ipv6 -H fd://
```

This is the output in the serf.log:
```
[root@9cf1d2623316 kong]# tail /tmp/serf.log
    2016/02/23 23:51:07 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:7946: accept4: operation not permitted
    2016/02/23 23:51:07 [ERR] agent.ipc: Failed to accept client: accept tcp 127.0.0.1:7373: accept4: operation not permitted
    2016/02/23 23:51:07 [ERR] memberlist: Error accepting TCP connection: accept tcp [::]:7946: accept4: operation not permitted
    2016/02/23 23:51:07 [ERR] agent.ipc: Failed to accept client: accept tcp 127.0.0.1:7373: accept4: operation not permitted
```

Kong version:
```
[root@9cf1d2623316 kong]# kong version
Kong version: 0.6.1
```

**Comment by ambrons** [comment]
Could #21 have something to do with this?  I know I'm having issues with #19.  I'm using the latest version of Docker Toolbox:
 * Docker version 1.10.1, build 9e83765
 * docker-machine version 0.6.0, build e27fb87
 * docker-compose version 1.6.0, build d99cad6

**Comment by gottfrois** [comment]
Running kong like this solved the issue:

```
docker run -d --name kong \
            --link cassandra:cassandra \
            -p 8000:8000 \
            -p 8443:8443 \
            -p 8001:8001 \
            -p 7946:7946 \
            -p 7946:7946/udp \
            --security-opt seccomp:unconfined \
            mashape/kong
```

```
$ docker exec -it kong tail -n 100 /tmp/serf.log
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
         Node name: '799b7f83fe2d_0.0.0.0:7946'
         Bind addr: '0.0.0.0:7946'
          RPC addr: '127.0.0.1:7373'
         Encrypted: false
          Snapshot: false
           Profile: wan

==> Log data will now stream in as it occurs:

```

See https://github.com/Mashape/docker-kong/issues/23

**Comment by gottfrois** [comment]
It also solved my curl commands freezing

**Comment by thefosk** [comment]
Nice - I will update the website and docker documentation with the findings at #19.
