### ISSUE TITLE
Can't find nginx error after startup

### ISSUE THREAD

**Issue by chicoandrade** [Mashape/docker-kong#28]
Hi there,

I'm having a recurrent problem on my kong 0.7.0 containers that a few seconds after the container goes up, it crashes with the message "Can't find nginx"

Here is the full log messages on the container startup
> [0m[34m[INFO] [0m[0mKong 0.7.0
> [0m[34m[INFO] [0m[0mUsing configuration: /etc/kong/kong.yml
> [0m[34m[INFO] [0m[0mSetting working directory to /usr/local/kong
> [0m[34m[INFO] [0m[0mdatabase...........cassandra auth=password=<password> username=<username> timeout=5000 data_centers= password=<password> ssl=verify=false enabled=false contact_points=<host>:<port> replication_strategy=SimpleStrategy username=<cassandra> replication_factor=1 keyspace=kong
> [0m[34m[INFO] [0m[0mdnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
> [0m[34m[INFO] [0m[0mserf ..............-profile=wan -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -advertise=<my_ip>:7946 -node=<hostname>_0.0.0.0:7946 -log-level=err
> [0m[34m[INFO] [0m[0mTrying to auto-join Kong nodes, please wait..
> [0m[33m[WARN] [0m[0mCannot join <cassandra_node_ip>:<port>. If the node does not exist anymore it will be automatically purged.
> [0m[34m[INFO] [0m[0mSuccessfully auto-joined <another_cassandra_node_ip>:<port>
> [0m[34m[INFO] [0m[0mAuto-generating the default SSL certificate and key...
> [0m[34m[INFO] [0m[0mLeaving cluster..
> [0m[31m[ERR] [0m[0mCan't find nginx
> [0m[31m[ERR] [0m[0mCould not start Kong

Can someone help me please?

**Comment by chicoandrade** [comment]
I am also trying to find the solution on this issue at kong github repo:
https://github.com/Mashape/kong/issues/610

**Comment by allisthere2love** [comment]
As we discovered investigating the issue with @thibaultCha, the problem occurs when the Ruxit agent is running in the host.

**Comment by allisthere2love** [comment]
Hi, just a new info in the ruxit/kong/nginx issue
The problem occurs when the ruxit agent is up-to-date, in version 1.8.9
Previous versions of the agent doesn't cause the issue

**Comment by chicoandrade** [comment]
Just to give everyone a feedback about this problem.
Ruxit team has launched a new agent version, 1.91, that has the fix for the problem.

We tested it and Kong is working fine with the new agent.
