### ISSUE TITLE
Overriding config items

### ISSUE THREAD

**Issue by EwanValentine** [Mashape/docker-kong#35]
When overriding configuration, do I override the entire `kong.yml` file with a complete config, or can I just include the lines that I wish to override?

**Comment by alexraju** [comment]
You will be overriding the entire kong.yml file.

**Comment by thibaultCha** [comment]
The only mandatory property in the current kong.yml file is the `nginx` one. Otherwise, you can only provide a subset of the complete YAML properties, overriding only the properties you want to, others will stick to their default values.

**Comment by EwanValentine** [comment]
Great thanks!
