### ISSUE TITLE
Kong won't start without a database

### ISSUE THREAD

**Issue by bradwood** [Mashape/docker-kong#37]
I'm trying to get docker compose working but it always brings up the kong container before the postres one... Apparently it's bad design for microservices to die if their dependencies are not up, they should keep trying to connect. Can you make Kong behave like this please?

In any event, this is all making it impossible for me to make this docker-compose work.  Can you please fix/provide workaround/comment.

thanks

**Comment by DonMartin76** [comment]
A common way of doing this is to use `dockerize`. The following `Dockerfile` will extend the `kong` image and makes Kong wait for Postgres:

```Dockerfile
FROM mashape/kong:latest

ENV DOCKERIZE_VERSION v0.2.0

RUN yum install -y epel-release && yum install -y wget \
    && yum clean all

RUN wget -nv https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY config.docker/kong.yml /etc/kong/kong.yml

#CMD [ "kong", "start" ]
CMD dockerize -wait tcp://kong-database:5432 kong start
```

**Comment by thefosk** [comment]
For 0.9 we have released an official Docker Compose template: https://github.com/Mashape/docker-kong/tree/master/compose
