### ISSUE TITLE
Kong hangs on [INFO] Auto-generating the default SSL certificate and key...

### ISSUE THREAD

**Issue by mckn** [Mashape/docker-kong#43]
Hello,

I hope I just missed something but I have a problem running KONG with docker. If I tries to run it without -t (tty) it doesn't output any logs.

If I run it with the -t (tty) it get stuck in this step: [INFO] Auto-generating the default SSL certificate and key...

I am trying to run integration tests against KONG in a container. And the same thing there, it hangs as soon as a child process is spawn.

**Comment by thefosk** [comment]
Does this still happen? @mckn

**Comment by mckn** [comment]
I will give it a try on the latest verson

**Comment by mckn** [comment]
hmm, I think it is working but it stop printing to the stdout. So I guess you can close this one.
