### ISSUE TITLE
Kong not able to link when started with composer 

### ISSUE THREAD

**Issue by tushardwivedi** [Mashape/docker-kong#46]
When trying to link kong to cassandra db via compose up, Kong is not able to connect to cassandra container. However same is working perfectly when i try to link manually from command line. 
I also tried with docker-machine ip in kong.yml, but got same error.  

Error after compose up:
" 
Tushars-MBP:docker-kong tushar$ docker logs 534e5cc8b4a0 
[INFO] kong 0.8.2
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra contact_points=kong-database:9042 data_centers= ssl=verify=false enabled=false port=9042 timeout=5000 replication_strategy=SimpleStrategy keyspace=kong replication_factor=1 consistency=ONE
[INFO] Leaving cluster..
[ERR] All hosts tried for query failed. kong-database:9042: connection refused for socket with peer kong-database:9042.
[ERR] Could not start Kong
"
**Compose file:** 
"
kong-database:
 image: cassandra:2.2
 hostname: kong-database
 ports:
- "9042:9042"

kong:
 image: mashape/kong:0.8.2
 ports:
- "8000:8000"
- "8001:8001"
- "8443:8443"

links:
- kong-database:kong-database

environment:
- DATABASE=cassandra
  "

**Docker info:**

"
Tushars-MBP:docker-kong tushar$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 44
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: handler
ID: BJHX:OKR3:YWIU:MAX5:PIR4:2I2J:C36B:TEHT:FQEJ:6IYT:6THT:EJHN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 30
 System Time: 2016-08-11T05:57:34.512054505Z
 EventsListeners: 0
Username: tushardwivedi
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
"

**Comment by thefosk** [comment]
Just so you know we now have an official Docker Compose template at https://github.com/Mashape/docker-kong/tree/master/compose

I think in your case the problem was that you are missing `restart: always` when defining the Kong image.
