### ISSUE TITLE
Incorrect date/time using docker-compose

### ISSUE THREAD

**Issue by typingincolor** [Mashape/docker-kong#52]
I have successfully started up things using the docker-compose file can send requests to kong.

I have configure the hmac plugin, but all my requests are 403-ing.

Have done some investigation the system time in the docker container is set incorrectly.

The container time is `Tue Aug 23 15:48:20 UTC 2016` but my system time is `Wed 24 Aug 2016 23:43:31 BST`

**Comment by thefosk** [comment]
Possibly a problem in the way Docker is configured?
