### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by jney** [Mashape/docker-kong#53]
hi. would it be possible to have some support about configuring docker's kong image?
i need to add a specific lua script that should be runned by openresty (something i want to run after `kong.access()` call), so i updated `nginx-kong.conf` and add my command after`access_by_lua_block`, i updated my own `Dockerfile` like this.

```docker
COPY config/nginx-kong.conf /usr/local/kong/
```

but it seems the file is overwritten.
is it the way to go? if yes what is the appropriate file to overwrite?
or should i use templates or something else?
thank you

**Comment by thibaultcha** [comment]
You should indeed use templates as described at https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration-amp-embedding-kong

**Comment by thibaultcha** [comment]
It seems the markdown formatting stripped out the variable names in the template. See 
https://github.com/Mashape/kong/tree/master/kong/templates
https://github.com/Mashape/kong/blob/master/spec/fixtures/custom_nginx.template

For good template examples and how `nginx.conf` and `nginx-kong.conf` are different, In your case, you'd want to modify what is in `nginx-kong.conf`, and for now, you'd have to follow the `custom_nginx.template` example, where the ngx_lua (Kong) config is inlined in the main nginx conf.

**Comment by jney** [comment]
thank you @thibaultcha
