### ISSUE TITLE
kong Nginx URL

### ISSUE THREAD

**Issue by saithala** [Mashape/docker-kong#54]
Im trying to run the example provided with Consul and Nginx using the compose. Once everything was up and running I tried to access Kong from the Kong Dashboard through Nginx instance. What would the URL to access Kong admin API? I tried http://nginx-lb:8001 and its not accessible. Im using Kong 0.9. I also tried to attach to the nginx container and ping'ed the "proxy_pass" (kong-8001) but got a host not found error. Any idea what im doing wrong? What would be the URL to access the kong admin api through the nginx reverse proxy?

**Comment by thefosk** [comment]
`http://127.0.0.1:8001`

**Comment by saithala** [comment]
@thefosk unfortunately this did not work. Could you please elaborate ?

**Comment by thibaultcha** [comment]
Which Consul example are you talking about? Not familiar with it but the Admin API is by default listening on port `8001`, that's about as far as we can help, the rest depends on your infrastructure.

**Comment by thefosk** [comment]
By using that Compose file, Kong will be available on `127.0.0.1:8001` - if you are using OSX, make sure that you have properly configured VirtualBox with the proper Port Forwarding settings.

**Comment by saithala** [comment]
thanks for your response @thefosk . We are trying to deploy it on Red Hat linux. I started the services using compose and scaled Kong service to 3. On the Admin UI, at the place where I need to configure the Kong node URL, as you suggested I configured http://127.0.0.1:8001. That is when I get this error message saying Kong is not accessible with this url/port

**Comment by sinzone** [comment]
@saithala what Kong Admin UI are you referring to? We don't provide nor directly support any Admin UI at the moment.

**Comment by saithala** [comment]
@sinzone I understand that Kong does not provide an Admin UI at the moment. I'm trying to use kong-dashboard from here https://github.com/PGBI/kong-dashboard . Its working perfectly fine if i just have an instance of Kong. Its just that Kong is not reachable when I front it through a Nginx + Consul set up described here https://github.com/Mashape/docker-kong/tree/master/compose .
