### ISSUE TITLE
Cannot start nginx-lb

### ISSUE THREAD

**Issue by aditya-mittal** [Mashape/docker-kong#57]
I have checked out your code and tried starting with docker-compose up. But it fails saying
`ERROR: for nginx-lb  Cannot start service nginx-lb: driver failed programming external connectivity on endpoint compose_nginx-lb_1 (45fe13a6dd43c580f6bf946ee14ba0630cfca2ae3c73ce23e3b712a5a1ac5a75): Bind for 0.0.0.0:8443 failed: port is already allocated`

**Comment by thefosk** [comment]
Make sure port `8443` is not already being used by another process (ie, another Kong running locally).

**Comment by aditya-mittal** [comment]
Hey to confirm port 8443 was not used by any other process

**Comment by thefosk** [comment]
This is a Docker problem with your host and configuration - you can try to assign different ports in the `docker-compose.yml` file to see if it works (or disable port `8443` completely just for the sake of testing).
