### ISSUE TITLE
New tags aren't getting pushed to docker hub

### ISSUE THREAD

**Issue by erutherford** [Mashape/docker-kong#58]
It looks like `0.9.1` and `0.9.2` should have been pushed to docker hub, but I'm not seeing them up there.

**Comment by hnq90** [comment]
`0.9.3` has been released but seem it hasn't not pushed yet on Docker Hub: https://hub.docker.com/r/library/kong/tags/

**Comment by hnq90** [comment]
Haven't merged yet: https://github.com/docker-library/official-images/pull/2230

**Comment by thefosk** [comment]
I will always push the latest version for each major version. ie: if we have 0.9.4 but we release 0.9.5, then 0.9.5 becomes the latest one and 0.9.4 disappears.

Incremental versions of the same baseline are non-breaking and retro-compatible.
