### ISSUE TITLE
Provide alpine linux version

### ISSUE THREAD

**Issue by ismailbaskin** [Mashape/docker-kong#61]

**Comment by ismailbaskin** [comment]
Maybe this can be helpful https://github.com/orangesys/alpine-kong

**Comment by hnq90** [comment]
@ismailbaskin Thank you. It's appropriate if we have an official image of Kong which base on Alpine.

**Comment by mudrii** [comment]
++1

**Comment by thefosk** [comment]
Available at `kong:0.11-alpine`.
