### ISSUE TITLE
Kong v0.9.6 on Docker Hub

### ISSUE THREAD

**Issue by hnq90** [Mashape/docker-kong#62]
Kong has just released version 0.9.6 but I coudn't see that tag on [Docker Hub](https://hub.docker.com/_/kong/)

**Comment by thefosk** [comment]
Latest 0.9.x is 0.9.9 which is available there. Latest version of Kong as we speak is 0.11.0 though.

Docker always takes a few hours to update because the release process requires a third-party validation by Docker.
