### ISSUE TITLE
kong Run with --v (verbose) or --vv (debug) 

### ISSUE THREAD

**Issue by AntonioCS** [Mashape/docker-kong#66]
Hey,

I sometimes have issues with kong and I get the msg:

> Run with --v (verbose) or --vv (debug) 

The Dockerfile has the command 

> CMD ["kong", "start"]

I am creating my own image because i need to put plugins code into kong, so I have something like this:

```
FROM kong:0.9.5

COPY ...
COPY ...
COPY ...
    
ENV DATABASE postgres 

```
Now.. is there a way for me to start kong in debug mode or do I have clone this repo and change the cmd to the debug mode?

If there is no way could some dev put the kong start in the docker-entrypoint.sh? I can override that in my image without issues.

Thanks

**Comment by patricksanders** [comment]
A CMD entry in your Dockerfile will override the one in the base Dockerfile.

Adding the last line here to your Dockerfile should do what you want:
```
FROM kong:0.9.5

COPY ...
COPY ...
COPY ...
    
ENV DATABASE postgres 

CMD ["kong", "start", "-vv"]
```

**Comment by AntonioCS** [comment]
Oh thanks. I really thought that could not be overwritten.
