### ISSUE TITLE
nginx-lb reload-nginx failed!

### ISSUE THREAD

**Issue by phiedulxp** [Mashape/docker-kong#88]
nginx-lb_1        | time="2017-06-18T01:03:00Z" level=debug msg=preStart.Cmd.Run
nginx-lb_1        | time="2017-06-18T01:03:00Z" level=error msg="fork/exec /bin/reload-nginx.sh: permission denied"

**Comment by prolic** [comment]
@phiedulxp I have the same problem. How did you solve it?

**Comment by Hello-Mango** [comment]
@phiedulxp  I have the same problem. How did you solve it?

**Comment by Hello-Mango** [comment]
@prolic you can add `CMD "chmod +x /bin/reload-nginx.sh"` on nginx\dockerfile,and now is work fine
