### ISSUE TITLE
I cannot start the docker-kong container, who can help me pls?

### ISSUE THREAD

**Issue by feikiss** [Mashape/docker-kong#9]
When I test whether the container is running normally, I met the following error:

{"message":"Cassandra error: Error during UNIQUE check: Cassandra error: cassandra could not be resolved (2: Server failure)"}

The following is the details:

[root@9fdc4a788c41 opt]# curl -i -X POST \
-data 'name=mockbin' \
 --data 'target_url=http://mockbin.com/' \
 --data 'public_dns=mockbin.com'>  --url http://localhost:8001/apis/ \
>  --data 'name=mockbin' \
>  --data 'target_url=http://mockbin.com/' \
>
HTTP/1.1 400 Bad Request
Date: Wed, 29 Jul 2015 06:43:26 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.2.1

{"public_dns":"public_dns is required"}
[root@9fdc4a788c41 opt]# curl -i -X POST \
-data 'name=mockbin' \
 --data 'target_url=http://mockbin.com/' \
 --data 'public_dns=mockbin.com'>  --url http://localhost:8001/apis/ \
>  --data 'name=mockbin' \
>  --data 'target_url=http://mockbin.com/' \
>  --data 'public_dns=mockbin.com'
HTTP/1.1 500 Internal Server Error
Date: Wed, 29 Jul 2015 06:44:32 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.2.1

{"message":"Cassandra error: Error during UNIQUE check: Cassandra error: cassandra could not be resolved (2: Server failure)"}

who can help me to go through it pls?

**Comment by thefosk** [comment]
@feikiss can you try again with the newest version 0.6.1?
