### ISSUE TITLE
Can't deploy Kong on DC/OS with HOST networking when listening on port 80

### ISSUE THREAD

**Issue by s-shine-s** [Mashape/docker-kong#94]
I am attempting to have kong listen on port 80 instead of 8000, and I updated the /usr/local/kong/nginx-kong.conf and Dockerfile to rebuilt the image:
server {
server_name kong;
listen 0.0.0.0:80;
……
}
Dockerfile:
FROM kong:0.10.3
COPY nginx-kong.conf  /usr/local/kong/nginx-kong.conf
EXPOSE 80 8443 8001 7946

DC/OS network definition:

NETWORK TYPE: **HOST**
NAME | PROTOCOL | HOST PORT | LOAD BALANCED ADDRESS |  
-- | -- | -- | -- | --
kong | tcp | 80 | kong.marathon.l4lb.thisdcos.directory:80 |  
kong-admin | tcp | 8001 | kong-admin.marathon.l4lb.thisdcos.directory:8001 |  
kong-ssl | tcp | 8443 | Not Enabled |  
kong-admin-ssl | tcp | 8444 | kong-admin-ssl.marathon.l4lb.thisdcos.directory:8444 |  
kong-serf-tcp-udp | udp, tcp | 7946 | Not Enabled

I've checked these ports are available, but Kong can't be deployed, why?

**Comment by thefosk** [comment]
Don't update the NGINX configuration file directly. Instead either update `kong.conf` or set the `KONG_PROXY_LISTEN=0.0.0.0:80` environment variable instead.
